name: demo-action

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      run: echo hello,word
    - name: cache
      run: echo hello,word
    - name: install
      run: echo hello,word
    - name: nuild
      run: echo hello,word
    - name: publish
      run: echo hello,word
